# Generated by Django 5.0.6 on 2024-07-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_company_active_alter_company_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='role',
            new_name='chosen_plan',
        ),
    ]
