# Generated by Django 5.0.6 on 2024-07-05 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=19)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('cep', models.CharField(blank=True, max_length=11)),
                ('city', models.CharField(max_length=100)),
                ('state', models.EmailField(max_length=20)),
                ('chosen_plan', models.IntegerField(choices=[(1, 'Gratis'), (2, 'Básico'), (3, 'Premium')], default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('active', models.BooleanField(default=True)),
                ('linked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='post_img')),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.category')),
                ('linked_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_company', to='business.company')),
            ],
        ),
    ]
